# Generated by Django 5.2.1 on 2025-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
