# Generated by Django 5.2.1 on 2025-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uploadeddocument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
