# Generated by Django 5.2.1 on 2025-08-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tag_test_testquestion_studenttagperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadeddocument'),
        ),
    ]
