# Generated by Django 5.2.1 on 2025-08-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_qa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='doc_type_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.uploadeddocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qa',
            name='type',
            field=models.IntegerField(),
        ),
    ]
