# Generated by Django 5.2.1 on 2025-08-08 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_qa_doc_type_num_alter_qa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(null=True),
        ),
    ]
